const products = [
    {
      id: 'rec43w3ipXvP28vog',
      title: 'high-back bench',
      company: 'ikea',
      image: './images/img1.jpeg',
      price: 9.99,
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
    },
    {
      id: 'rec4f2RIftFCb7aHh',
      title: 'albany table',
      company: 'marcos',
      image: './images/img2.jpeg',
      price: 79.99,
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
    },
    {
      id: 'rec8kkCmSiMkbkiko',
      title: 'accent chair',
      company: 'caressa',
      image: './images/img3.jpeg',
      price: 25.99,
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
    },
    {
      id: 'recBohCqQsot4Q4II',
      title: 'wooden table',
      company: 'caressa',
      image: './images/img4.jpeg',
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
  
      price: 45.99,
    },
    {
      id: 'recDG1JRZnbpRHpoy',
      title: 'dining table',
      company: 'caressa',
      image: './images/img5.webp',
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
      price: 6.99,
    },
    {
      id: 'recNWGyP7kjFhSqw3',
      title: 'sofa set',
      company: 'liddy',
      image: './images/img6.jpeg',
      price: 69.99,
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
    },
    {
      id: 'recZEougL5bbY4AEx',
      title: 'modern bookshelf',
      company: 'marcos',
      image: './images/img7.jpeg',
      price: 8.99,
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
    },
    {
      id: 'recjMK1jgTb2ld7sv',
      title: 'emperor bed',
      company: 'liddy',
      image: './images/img8.jpeg',
      price: 21.99,
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
    },
    {
      id: 'recmg2a1ctaEJNZhu',
      title: 'utopia sofa',
      company: 'marcos',
      image: './images/img9.jpeg',
      price: 39.95,
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
    },
    {
      id: 'recvKMNR3YFw0bEt3',
      title: 'entertainment center',
      company: 'liddy',
      image: './images/img10.jpeg',
      price: 29.98,
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
    },
    {
      id: 'recxaXFy5IW539sgM',
      title: 'albany sectional',
      company: 'ikea',
      image: './images/img11.jpeg',
      price: 10.99,
      parag :  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
    },
    {
      id: 'recyqtRglGNGtO4Q5',
      title: 'leather sofa',
      company: 'liddy',
      image: './images/img12.jpg',
      price: 9.99,
      parag : "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet quod, ea quas ipsam nemo officia possimus velit autem vitae maiores rerum cumque repudiandae dolore facilis cupiditate explicabo nostrum. Atque, voluptas.,",
    },
  ];
  